runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: templates/css

- url: /img
  static_dir: templates/img

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: "latest"
